//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class access
    {
        public int id { get; set; }
        public int id_user { get; set; }
        public Nullable<bool> access_config { get; set; }
        public string name_access_config { get; set; }
    
        public virtual account account { get; set; }
    }
}
