//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class config_planar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public config_planar()
        {
            this.connect_planar_config = new HashSet<connect_planar_config>();
            this.connect_planar_config1 = new HashSet<connect_planar_config>();
            this.connect_planar_config2 = new HashSet<connect_planar_config>();
            this.connect_planar_config3 = new HashSet<connect_planar_config>();
            this.connect_planar_config4 = new HashSet<connect_planar_config>();
            this.connect_planar_config5 = new HashSet<connect_planar_config>();
            this.connect_planar_config6 = new HashSet<connect_planar_config>();
        }
    
        public int id { get; set; }
        public System.DateTime time_stamp { get; set; }
        public double curvcenter_c { get; set; }
        public double curvcenter_v { get; set; }
        public double curv_av { get; set; }
        public double curv_bv { get; set; }
        public double curv_ac { get; set; }
        public double curv_bc { get; set; }
        public double twist { get; set; }
        public double contrd { get; set; }
        public double corner_p { get; set; }
        public double corner_n { get; set; }
        public int grade_config { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<connect_planar_config> connect_planar_config { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<connect_planar_config> connect_planar_config1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<connect_planar_config> connect_planar_config2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<connect_planar_config> connect_planar_config3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<connect_planar_config> connect_planar_config4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<connect_planar_config> connect_planar_config5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<connect_planar_config> connect_planar_config6 { get; set; }
    }
}
