//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tile_group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tile_group()
        {
            this.tiles = new HashSet<tile>();
        }
    
        public int id { get; set; }
        public int id_user { get; set; }
        public int id_planar_config { get; set; }
        public int id_calibre_config { get; set; }
    
        public virtual account account { get; set; }
        public virtual connect_calibre_config connect_calibre_config { get; set; }
        public virtual connect_planar_config connect_planar_config { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tile> tiles { get; set; }
    }
}
