//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tile()
        {
            this.errors = new HashSet<error>();
        }
    
        public int id { get; set; }
        public int id_g { get; set; }
        public int id_planar_details { get; set; }
        public int id_calibre_details { get; set; }
        public int id_planar_grade { get; set; }
        public int id_calibre_grade { get; set; }
        public int id_grade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<error> errors { get; set; }
        public virtual grade grade { get; set; }
        public virtual tile_calibre_details tile_calibre_details { get; set; }
        public virtual tile_calibre_grade tile_calibre_grade { get; set; }
        public virtual tile_group tile_group { get; set; }
        public virtual tile_planar_details tile_planar_details { get; set; }
        public virtual tile_planar_grade tile_planar_grade { get; set; }
    }
}
