//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tile_calibre_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tile_calibre_details()
        {
            this.tiles = new HashSet<tile>();
        }
    
        public int id { get; set; }
        public System.DateTime time_stamp { get; set; }
        public double difference_a { get; set; }
        public double difference_b { get; set; }
        public double parallelism_a { get; set; }
        public double parallelism_b { get; set; }
        public double curvat_a { get; set; }
        public double curvat_b { get; set; }
        public double curvat_x2_a { get; set; }
        public double curvat_x2_b { get; set; }
        public double ortogon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tile> tiles { get; set; }
    }
}
