//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tile_planar_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tile_planar_details()
        {
            this.tiles = new HashSet<tile>();
        }
    
        public int id { get; set; }
        public System.DateTime time_stamp { get; set; }
        public double curvcenter { get; set; }
        public double curv_a { get; set; }
        public double curv_b { get; set; }
        public double twist { get; set; }
        public double contrd { get; set; }
        public double corner_p { get; set; }
        public double corner_n { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tile> tiles { get; set; }
    }
}
