//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tile_planar_grade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tile_planar_grade()
        {
            this.tiles = new HashSet<tile>();
        }
    
        public int id { get; set; }
        public System.DateTime time_stamp { get; set; }
        public int grade_curvcenter { get; set; }
        public int grade_curv_a { get; set; }
        public int grade_curv_b { get; set; }
        public int grade_twist { get; set; }
        public int grade_contrd { get; set; }
        public int grade_corner { get; set; }
        public int grade_planar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tile> tiles { get; set; }
    }
}
